### ISSUE TITLE
No caffe.Net and caffe.TRAIN

### ISSUE THREAD

**Issue by Matrix-Jian** [abner2015/tensorflow2caffemodel#6]
你好，

我运行代码时，提示caffe没有Net，TRAIN属性。请问这个问题是什么原因？

十分感谢！

**Comment by abner2015** [comment]
详细的报错信息是什么

**Comment by Matrix-Jian** [comment]
File "tf2caffe.py", line 72, in <module>
    tf2caffe(checkpoint_path, cf_prototxt, cf_model)
  File "tf2caffe.py", line 27, in tf2caffe
    net = caffe.Net(cf_prototxt, caffe.TRAIN)
AttributeError: module 'caffe' has no attribute 'Net'

**Comment by abner2015** [comment]
安装了caffe python吗

**Comment by Matrix-Jian** [comment]
请问这个需要如何安装？

**Comment by abner2015** [comment]
Makefile.config 将
#WITH_PYTHON_LAYER := 1 
修改为 
WITH_PYTHON_LAYER := 1

**Comment by Matrix-Jian** [comment]
我一直没找到Makefile.config文件

**Comment by abner2015** [comment]
建议你google一下，caffe编译python接口

**Comment by Matrix-Jian** [comment]
好的，十分感谢！
