### ISSUE TITLE
caffe 和 tf 能兼容吗

### ISSUE THREAD

**Issue by Smezzdl** [abner2015/tensorflow2caffemodel#7]
caffe 和tf能安装在一个环境下吗 会不会不兼容 目前正在安装caffe 网上的教程都是分别安装的

**Comment by abner2015** [comment]
可以，就相当于安装了两个软件，只不过gpu资源可能不能同时用

**Comment by Smezzdl** [comment]
请问 转换后如果需要对单张图片进行预测 是不是只需要 caffemodel、prototxt文件 、原图片 、label的txt文件就可以了

**Comment by abner2015** [comment]
是的，其实就和caffe预测一样
